version: '3.8'

services:
  feelem-app:
    image: feelem-springboot-app:latest # ⬅️ 'build' 대신 'image' 사용
    container_name: feelem-spring-boot
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # ... (DB 등 다른 환경 변수) ...
    volumes:
      - spring_boot_logs:/app/logs
    restart: always

volumes:
  spring_boot_logs: