spring:
  application:
    name: feelem
  profiles:
    active: prod # local, dev, prod

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:mysql://feelem-mysql.cbmgucewogo4.ap-northeast-2.rds.amazonaws.com:3306/feelem?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: feelem
    password: WonderDogs1001
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # update, crate, create-drop, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    show-sql: false

  cloud:
    openfeign: #
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 10000

jwt:
  secret: dGhpcy1pcy1hLXZlcnktbG9uZy1hbmQtc2VjdXJlLXNlY3JldC1rZXktZm9yLWp3dC0yMDI1 #Base64 Encode

cloud:
  aws:
    s3:
      bucket: feelem-s3-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

recommend:
  server:
    url: http://172.31.44.15:8080

generate:
  server:
    url: http://172.31.1.180

server:
  port: 80

google:
  client-id: "27326569433-37asc7ec60uq68sujfe3ooaud6i9puo7.apps.googleusercontent.com"